import React from 'react'
import Head from 'next/head'
import { NextPage, GetStaticProps } from 'next'
import tw from 'twin.macro'
import Link from 'next/link'
import Sidenav from 'src/components/sidenav'
import { getSheetList } from 'src/utils/sheet_product'

const testStyles = {
  // Move long class sets out of jsx to keep it scannable
  container: ({ hasBackground }) => [
    tw`flex flex-col items-center justify-center h-screen`,
    hasBackground && tw`bg-gradient-to-b from-gray-50 to-gray-200`,
  ],
}

interface Props {
  sheetData: SheetGlobal.ProductItems | null
}

const Home: NextPage<Props> = ({ sheetData }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidenav />

      <div css={testStyles.container({ hasBackground: true })}>
        <div tw="flex flex-col justify-center h-10 gap-y-5">
          <p>{JSON.stringify(sheetData)}</p>
        </div>
        <div>Index</div>
      </div>
    </div>
  )
}

// export const getStaticProps: GetStaticProps = async () => {
//   const sheetName = 'Products'
//   const data = await getSheetList(sheetName)
//   return {
//     props: {
//       sheetData: data, // remove sheet header
//     },
//   }
// }

export default Home
