import React from 'react'
import Head from 'next/head'
import { NextPage } from 'next'
import Sidenav from 'src/components/sidenav'
import Layout from 'src/components/layout'
import Home from 'src/components/home'
import About from 'src/components/about'

interface Props {
  sheetData: SheetGlobal.ProductItems | null
}
const title = '測試標題'
const subtitle = '次標題內容文字'

const Index: NextPage<Props> = ({ sheetData }: Props) => {
  return (
    <Layout title="Home" description={`${title} - ${subtitle}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidenav />
      <main>
        <Home />
        <About />
      </main>
      <p>{JSON.stringify(sheetData)}</p>
    </Layout>
  )
}

// export const getStaticProps: GetStaticProps = async () => {
//   const sheetName = 'Products'
//   const data = await getSheetList(sheetName)
//   return {
//     props: {
//       sheetData: data, // remove sheet header
//     },
//   }
// }

export default Index
