import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import tw from 'twin.macro'
import Button from 'src/components/Button'
import Link from 'next/link'
import Sidenav from 'src/components/Sidenav'
import { getSheetList } from 'src/utils/sheet_product'

const testStyles = {
  // Move long class sets out of jsx to keep it scannable
  container: ({ hasBackground }) => [
    tw`flex flex-col items-center justify-center h-screen`,
    hasBackground && tw`bg-gradient-to-b from-gray-50 to-gray-200`,
  ],
}

interface Props {
  sheetData: SheetGlobal.ProductItems | null
}

const Home: NextPage<Props> = ({ sheetData }) => {
  // console.log(sheetData)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidenav />

      <div css={testStyles.container({ hasBackground: true })}>
        <div tw="flex flex-col justify-center h-10 gap-y-5">
          <p>Test</p>
        </div>
        <Button variant="primary">Submit</Button>
        <Link href="/noodle">
          <a>Go to Noodle Page</a>
        </Link>
        <Link href="/gyoza">
          <a>Go to Gyoza Page</a>
        </Link>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const sheetName = 'Products'
  const data = await getSheetList(sheetName)
  return {
    props: {
      sheetData: data, // remove sheet header
    },
  }
}

export default Home
